### ISSUE TITLE
gulp build fails

### ISSUE THREAD

**Issue by cdaringe** [whoisandie/yoda#3]
hello,
on line 128, `'cp -R ./tmp/** <%= release_build %>/build/',` craps out. any tips?
thx!  impressive work!

**Comment by whoisandy** [comment]
@cdaringe Thanks for pointing out. Due to the incorrect environment variable used in the build process. All files are copied to a separate tmp directory when NODE_ENV is set to release in the compile process, which has been fixed by setting NODE_ENV to 'production'. To run the build task use the following script now.

`NODE_ENV='production' gulp build`
or
`npm run build`
